# Generated by Django 2.1.5 on 2019-01-10 14:25

import cloudinary.models
from django.db import migrations, models
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Items',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('name', models.CharField(max_length=25, verbose_name='Name')),
                ('image', models.CharField(max_length=100, verbose_name='Image')),
                ('category', models.CharField(max_length=15, verbose_name='Category')),
                ('comment', models.CharField(max_length=250, verbose_name='Comment')),
                ('imageFile', cloudinary.models.CloudinaryField(max_length=255, verbose_name='ImageFile')),
            ],
            options={
                'verbose_name': 'Item',
                'verbose_name_plural': 'Items',
                'ordering': ['name'],
            },
        ),
    ]
