# Generated by Django 2.1.5 on 2019-01-14 14:37

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='items',
            name='image',
            field=models.CharField(max_length=100, verbose_name='Image URL'),
        ),
        migrations.AlterField(
            model_name='items',
            name='imageFile',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='imageFile'),
        ),
    ]
