# Generated by Django 2.1.5 on 2019-01-14 17:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20190114_1237'),
    ]

    operations = [
        migrations.RenameField(
            model_name='items',
            old_name='image',
            new_name='imageURL',
        ),
    ]
